"""Scaffold minimal HTTP APIs (stdlib only) and OpenAPI stubs."""

from __future__ import annotations
from typing import Any, Dict, List, Optional
import os
import json

PROJECT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(PROJECT)

def _safe(path: str) -> str:
    abs_path = os.path.abspath(os.path.join(PROJECT, path) if not os.path.isabs(path) else path)
    return abs_path

def scaffold_http_api(name: str = "myapi", endpoints: Optional[List[str]] = None) -> Dict[str, Any]:
    endpoints = endpoints or ["health", "echo"]
    safe = "".join(c if c.isalnum() or c == "_" else "_" for c in name.lower())
    root = _safe(os.path.join("examples", "apis", safe))
    os.makedirs(root, exist_ok=True)
    server_py = f'''#!/usr/bin/env python3
"""Minimal API: {safe} — generated by LlmLang."""
from __future__ import annotations
from http.server import BaseHTTPRequestHandler, HTTPServer
import json
import urllib.parse
PORT = 8787
class Handler(BaseHTTPRequestHandler):
    def _json(self, code: int, obj):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)
    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path.rstrip("/") or "/"
        if path in ("/", "/health"):
            return self._json(200, {{"ok": True, "service": "{safe}"}})
        if path == "/echo":
            qs = urllib.parse.parse_qs(parsed.query)
            return self._json(200, {{"echo": qs}})
        self._json(404, {{"error": "not found", "path": path}})
    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        raw = self.rfile.read(length) if length else b"{{}}"
        try:
            data = json.loads(raw.decode() or "{{}}")
        except json.JSONDecodeError:
            data = {{"raw": raw.decode(errors="replace")}}
        path = urllib.parse.urlparse(self.path).path.rstrip("/") or "/"
        if path == "/echo":
            return self._json(200, {{"echo": data}})
        self._json(404, {{"error": "not found", "path": path}})
    def log_message(self, fmt, *args):
        print("[api]", fmt % args)
def main():
    httpd = HTTPServer(("0.0.0.0", PORT), Handler)
    print(f"Serving {safe} on http://127.0.0.1:{{PORT}}")
    httpd.serve_forever()
if __name__ == "__main__":
    main()
'''
    readme = f"# {safe}\n\nMinimal stdlib HTTP API generated by LlmLang.\n\n```bash\npython server.py\n```\n"
    openapi = {"openapi": "3.0.0", "info": {"title": safe, "version": "0.1.0"}, "paths": {"/health": {"get": {"summary": "Health", "responses": {"200": {"description": "OK"}}}}, "/echo": {"get": {"summary": "Echo", "responses": {"200": {"description": "OK"}}}, "post": {"summary": "Echo body", "responses": {"200": {"description": "OK"}}}}}}
    files = {os.path.join(root, "server.py"): server_py, os.path.join(root, "README.md"): readme, os.path.join(root, "openapi.json"): json.dumps(openapi, indent=2) + "\n"}
    written = []
    for path, content in files.items():
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(os.path.relpath(path, PROJECT))
    return {"ok": True, "name": safe, "dir": os.path.relpath(root, PROJECT), "files": written, "run": f"python {os.path.relpath(root, PROJECT)}/server.py"}

API_TOOLS: Dict[str, Dict[str, Any]] = {
    "scaffold_http_api": {
        "name": "scaffold_http_api",
        "description": "Scaffold a minimal stdlib HTTP API. Args: name, endpoints.",
        "parameters": {"type": "object", "properties": {"name": {"type": "string"}, "endpoints": {"type": "array", "items": {"type": "string"}}}, "required": ["name"]},
        "function": scaffold_http_api,
    },
}
