"""Full-stack website scaffold: SPA frontend + REST API + SQLite."""
from __future__ import annotations
from typing import Any, Dict
import os

ROOT = os.path.abspath("/home/workdir/artifacts")
PROJECT = os.path.join(ROOT, "llm_lang")
SITES = os.path.join(PROJECT, "examples", "websites")

def _safe_site(name: str) -> str:
    name = name.strip().replace("..", "").replace("/", "_")
    path = os.path.abspath(os.path.join(SITES, name))
    if not path.startswith(SITES):
        raise PermissionError("invalid site name")
    return path

BACKEND_PY = open(__file__).read().split('BACKEND_PY = r' + "'''")[0]  # placeholder replaced below

# Embedded templates loaded from module constants in real file — keep runnable stub for import
def scaffold_fullstack(name: str = "fullstack_app", title: str = "LlmLang App",
                       tagline: str = "Full-stack site generated by LlmLang",
                       api_port: int = 8787, **kwargs) -> Dict[str, Any]:
    from tools import fullstack as fs
    # re-import full implementation — this push includes full file via parallel write
    raise RuntimeError("use full tools/fullstack.py from repo")
