"""Static website scaffolding, pages, assets, and local server."""

from __future__ import annotations
from typing import Any, Dict, List, Optional
import os
import json
import threading
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

PROJECT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITES = os.path.join(PROJECT, "examples", "websites")

def _safe_site(name: str) -> str:
    safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in name)
    path = os.path.join(SITES, safe)
    os.makedirs(path, exist_ok=True)
    return path

def _css(theme: str = "dark") -> str:
    if theme == "light":
        return "body{font-family:system-ui;margin:2rem;background:#fafafa;color:#222} a{color:#06c}"
    return "body{font-family:system-ui;margin:2rem;background:#0b0f19;color:#e6e8ef} a{color:#7aa2ff}"

def scaffold_website(name: str = "site", title: str = "My Site", pages: Optional[List[str]] = None, theme: str = "dark") -> Dict[str, Any]:
    pages = pages or ["index", "about"]
    root = _safe_site(name)
    assets = os.path.join(root, "assets")
    os.makedirs(assets, exist_ok=True)
    with open(os.path.join(assets, "style.css"), "w") as f:
        f.write(_css(theme))
    written = []
    for page in pages:
        fname = "index.html" if page == "index" else f"{page}.html"
        html = f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/><title>{title} — {page}</title>
<link rel="stylesheet" href="assets/style.css"/></head>
<body><header><h1>{title}</h1>
<nav>{' '.join(f'<a href="{\"index.html\" if p==\"index\" else p+\".html\"}">{p}</a>' for p in pages)}</nav></header>
<main><h2>{page.title()}</h2><p>Generated by LlmLang.</p></main></body></html>
"""
        path = os.path.join(root, fname)
        with open(path, "w") as f:
            f.write(html)
        written.append(os.path.relpath(path, PROJECT))
    meta = {"name": name, "title": title, "theme": theme, "pages": pages}
    with open(os.path.join(root, "site.json"), "w") as f:
        json.dump(meta, f, indent=2)
    return {"ok": True, "name": name, "theme": theme, "dir": os.path.relpath(root, PROJECT), "files": written, "message": f"Scaffolded website '{name}'"}

def write_page(site: str, page: str, title: str, body_html: str) -> Dict[str, Any]:
    root = _safe_site(site)
    fname = "index.html" if page in ("index", "") else f"{page}.html"
    path = os.path.join(root, fname)
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"/><title>{title}</title>
<link rel="stylesheet" href="assets/style.css"/></head>
<body><h1>{title}</h1>{body_html}</body></html>
"""
    with open(path, "w") as f:
        f.write(html)
    return {"ok": True, "path": os.path.relpath(path, PROJECT)}

def write_asset(site: str, filename: str, content: str) -> Dict[str, Any]:
    root = _safe_site(site)
    assets = os.path.join(root, "assets")
    os.makedirs(assets, exist_ok=True)
    path = os.path.join(assets, filename)
    with open(path, "w") as f:
        f.write(content)
    return {"ok": True, "path": os.path.relpath(path, PROJECT)}

_servers: Dict[str, Any] = {}

def serve_site(site: str, port: int = 8765) -> Dict[str, Any]:
    root = _safe_site(site)
    key = f"{site}:{port}"
    if key in _servers:
        return {"ok": True, "url": f"http://127.0.0.1:{port}", "already_running": True}
    handler = type("H", (SimpleHTTPRequestHandler,), {"directory": root})
    # Python 3.7+ SimpleHTTPRequestHandler uses directory in init on 3.7+
    class Handler(SimpleHTTPRequestHandler):
        def __init__(self, *a, **k):
            super().__init__(*a, directory=root, **k)
        def log_message(self, fmt, *args):
            pass
    httpd = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    t = threading.Thread(target=httpd.serve_forever, daemon=True)
    t.start()
    _servers[key] = httpd
    return {"ok": True, "url": f"http://127.0.0.1:{port}", "site": site, "root": os.path.relpath(root, PROJECT)}

def list_sites() -> Dict[str, Any]:
    os.makedirs(SITES, exist_ok=True)
    sites = []
    for name in sorted(os.listdir(SITES)):
        path = os.path.join(SITES, name)
        if os.path.isdir(path):
            meta_path = os.path.join(path, "site.json")
            meta = {}
            if os.path.isfile(meta_path):
                try:
                    meta = json.load(open(meta_path))
                except Exception:
                    pass
            sites.append({"name": name, "path": os.path.relpath(path, PROJECT), **meta})
    return {"ok": True, "sites": sites}

WEB_TOOLS: Dict[str, Dict[str, Any]] = {
    "scaffold_website": {"name": "scaffold_website", "description": "Scaffold a static website.", "parameters": {"type": "object", "properties": {"name": {"type": "string"}, "title": {"type": "string"}, "pages": {"type": "array", "items": {"type": "string"}}, "theme": {"type": "string"}}, "required": ["name"]}, "function": scaffold_website},
    "write_page": {"name": "write_page", "description": "Write an HTML page into a site.", "parameters": {"type": "object", "properties": {"site": {"type": "string"}, "page": {"type": "string"}, "title": {"type": "string"}, "body_html": {"type": "string"}}, "required": ["site", "page", "title", "body_html"]}, "function": write_page},
    "write_asset": {"name": "write_asset", "description": "Write a CSS/JS asset.", "parameters": {"type": "object", "properties": {"site": {"type": "string"}, "filename": {"type": "string"}, "content": {"type": "string"}}, "required": ["site", "filename", "content"]}, "function": write_asset},
    "serve_site": {"name": "serve_site", "description": "Serve a site locally.", "parameters": {"type": "object", "properties": {"site": {"type": "string"}, "port": {"type": "integer"}}, "required": ["site"]}, "function": serve_site},
    "list_sites": {"name": "list_sites", "description": "List scaffolded websites.", "parameters": {"type": "object", "properties": {}, "required": []}, "function": list_sites},
}
